import React, { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from './ui/card';
import { Badge } from './ui/badge';
import { Button } from './ui/button';
import { 
  MapPin, 
  Calendar, 
  IndianRupee, 
  Users, 
  Clock, 
  Sun, 
  Car, 
  Hotel,
  ChevronDown,
  ChevronUp,
  Star,
  Camera,
  Utensils,
  ShoppingBag,
  Eye
} from 'lucide-react';

const Itinerary = ({ itinerary }) => {
  const [expandedDay, setExpandedDay] = useState(1);

  const getActivityIcon = (type) => {
    const iconMap = {
      transport: Car,
      sightseeing: Eye,
      dining: Utensils,
      shopping: ShoppingBag,
      photography: Camera
    };
    return iconMap[type] || MapPin;
  };

  const getActivityColor = (type) => {
    const colorMap = {
      transport: 'text-blue-700 bg-blue-100',
      sightseeing: 'text-amber-700 bg-amber-100',
      dining: 'text-red-700 bg-red-100',
      shopping: 'text-orange-700 bg-orange-100',
      photography: 'text-pink-700 bg-pink-100'
    };
    return colorMap[type] || 'text-amber-700 bg-amber-100';
  };

  return (
    <section className="px-6 relative">
      <div className="max-w-7xl mx-auto">
        {/* Header */}
        <div className="text-center mb-12 space-y-4">
          <Badge className="bg-gradient-to-r from-amber-100 to-orange-100 text-amber-800 border-amber-300">
            ✨ Generated by AI
          </Badge>
          <h2 className="text-4xl lg:text-5xl font-bold text-amber-900">
            Your Perfect <span className="bg-gradient-to-r from-amber-700 to-red-700 bg-clip-text text-transparent">Itinerary</span>
          </h2>
          <p className="text-xl text-amber-800">
            {itinerary.destination} • {itinerary.duration} • {itinerary.totalCost}
          </p>
        </div>

        <div className="grid lg:grid-cols-3 gap-8">
          {/* Left Column - Itinerary Details */}
          <div className="lg:col-span-2 space-y-6">
            {/* Trip Overview */}
            <Card className="backdrop-blur-lg bg-amber-50/40 border border-amber-200/50 shadow-lg">
              <CardContent className="p-6">
                <div className="grid md:grid-cols-4 gap-6">
                  <div className="text-center">
                    <div className="w-12 h-12 bg-gradient-to-r from-amber-600 to-red-600 rounded-full mx-auto mb-2 flex items-center justify-center">
                      <MapPin className="w-6 h-6 text-white" />
                    </div>
                    <div className="font-semibold text-amber-900">{itinerary.destination}</div>
                    <div className="text-sm text-amber-700">Destination</div>
                  </div>
                  <div className="text-center">
                    <div className="w-12 h-12 bg-gradient-to-r from-orange-600 to-red-600 rounded-full mx-auto mb-2 flex items-center justify-center">
                      <Calendar className="w-6 h-6 text-white" />
                    </div>
                    <div className="font-semibold text-amber-900">{itinerary.duration}</div>
                    <div className="text-sm text-amber-700">Duration</div>
                  </div>
                  <div className="text-center">
                    <div className="w-12 h-12 bg-gradient-to-r from-red-600 to-orange-600 rounded-full mx-auto mb-2 flex items-center justify-center">
                      <IndianRupee className="w-6 h-6 text-white" />
                    </div>
                    <div className="font-semibold text-amber-900">{itinerary.totalCost}</div>
                    <div className="text-sm text-amber-700">Total Cost</div>
                  </div>
                  <div className="text-center">
                    <div className="w-12 h-12 bg-gradient-to-r from-amber-600 to-orange-600 rounded-full mx-auto mb-2 flex items-center justify-center">
                      <Star className="w-6 h-6 text-white" />
                    </div>
                    <div className="font-semibold text-amber-900">4.8★</div>
                    <div className="text-sm text-amber-700">AI Rating</div>
                  </div>
                </div>
              </CardContent>
            </Card>

            {/* Daily Itinerary */}
            <div className="space-y-4">
              {itinerary.days.map((day) => (
                <Card 
                  key={day.day} 
                  className="backdrop-blur-lg bg-amber-50/40 border border-amber-200/50 shadow-lg hover:shadow-xl transition-all duration-300"
                >
                  <CardHeader 
                    className="cursor-pointer"
                    onClick={() => setExpandedDay(expandedDay === day.day ? null : day.day)}
                  >
                    <div className="flex items-center justify-between">
                      <div className="flex items-center space-x-4">
                        <div className="w-12 h-12 bg-gradient-to-r from-amber-600 to-red-600 rounded-full flex items-center justify-center text-white font-bold">
                          {day.day}
                        </div>
                        <div>
                          <CardTitle className="text-xl text-amber-900">{day.title}</CardTitle>
                          <div className="text-sm text-amber-700 flex items-center space-x-4">
                            <span>{day.date}</span>
                            <span>•</span>
                            <span className="flex items-center">
                              <Sun className="w-4 h-4 mr-1" />
                              {day.weather.temp}
                            </span>
                            <span>•</span>
                            <span className="flex items-center">
                              <IndianRupee className="w-4 h-4 mr-1" />
                              {day.dailyCost}
                            </span>
                          </div>
                        </div>
                      </div>
                      {expandedDay === day.day ? <ChevronUp className="text-amber-700" /> : <ChevronDown className="text-amber-700" />}
                    </div>
                  </CardHeader>

                  {expandedDay === day.day && (
                    <CardContent className="pt-0 pb-6">
                      <div className="space-y-4">
                        {/* Activities */}
                        <div className="grid gap-3">
                          {day.activities.map((activity, index) => {
                            const IconComponent = getActivityIcon(activity.type);
                            
                            return (
                              <div key={index} className="flex items-start space-x-4 p-4 rounded-lg bg-white/50 backdrop-blur-sm">
                                <div className="flex-shrink-0">
                                  <div className="text-sm font-medium text-amber-900 mb-1">{activity.time}</div>
                                  <div className={`w-8 h-8 rounded-full flex items-center justify-center ${getActivityColor(activity.type)}`}>
                                    <IconComponent className="w-4 h-4" />
                                  </div>
                                </div>
                                <div className="flex-1">
                                  <h4 className="font-semibold text-amber-900">{activity.activity}</h4>
                                  <p className="text-sm text-amber-700 flex items-center mt-1">
                                    <MapPin className="w-3 h-3 mr-1" />
                                    {activity.location}
                                  </p>
                                  <div className="mt-2 flex items-center justify-between">
                                    <Badge variant="outline" className="text-xs border-amber-300 text-amber-700">
                                      {activity.type.charAt(0).toUpperCase() + activity.type.slice(1)}
                                    </Badge>
                                    <span className="text-sm font-medium text-red-700">{activity.cost}</span>
                                  </div>
                                </div>
                              </div>
                            );
                          })}
                        </div>

                        {/* Day Summary */}
                        <div className="grid md:grid-cols-3 gap-4 mt-6 p-4 bg-amber-100/50 rounded-lg">
                          <div className="text-center">
                            <Hotel className="w-5 h-5 mx-auto mb-1 text-orange-700" />
                            <div className="text-sm font-medium text-amber-900">{day.accommodation}</div>
                            <div className="text-xs text-amber-700">Accommodation</div>
                          </div>
                          <div className="text-center">
                            <Car className="w-5 h-5 mx-auto mb-1 text-red-700" />
                            <div className="text-sm font-medium text-amber-900">{day.transport}</div>
                            <div className="text-xs text-amber-700">Transportation</div>
                          </div>
                          <div className="text-center">
                            <Sun className="w-5 h-5 mx-auto mb-1 text-amber-700" />
                            <div className="text-sm font-medium text-amber-900">
                              {day.weather.temp} • {day.weather.condition}
                            </div>
                            <div className="text-xs text-amber-700">Weather</div>
                          </div>
                        </div>
                      </div>
                    </CardContent>
                  )}
                </Card>
              ))}
            </div>
          </div>

          {/* Right Column - Trip Summary */}
          <div className="space-y-6">
            {/* Highlights */}
            <Card className="backdrop-blur-lg bg-amber-50/40 border border-amber-200/50 shadow-lg">
              <CardHeader>
                <CardTitle className="text-lg text-amber-900">Trip Highlights</CardTitle>
              </CardHeader>
              <CardContent className="space-y-3">
                {itinerary.highlights.map((highlight, index) => (
                  <div key={index} className="flex items-center space-x-3">
                    <Star className="w-4 h-4 text-amber-600" />
                    <span className="text-sm text-amber-800">{highlight}</span>
                  </div>
                ))}
              </CardContent>
            </Card>

            {/* Includes */}
            <Card className="backdrop-blur-lg bg-amber-50/40 border border-amber-200/50 shadow-lg">
              <CardHeader>
                <CardTitle className="text-lg text-amber-900">What's Included</CardTitle>
              </CardHeader>
              <CardContent className="space-y-3">
                {itinerary.includes.map((item, index) => (
                  <div key={index} className="flex items-center space-x-3">
                    <div className="w-2 h-2 bg-red-600 rounded-full"></div>
                    <span className="text-sm text-amber-800">{item}</span>
                  </div>
                ))}
              </CardContent>
            </Card>

            {/* Action Buttons */}
            <div className="space-y-3">
              <Button className="w-full bg-gradient-to-r from-amber-600 to-red-600 hover:from-amber-700 hover:to-red-700 text-white border-0">
                Book This Trip
              </Button>
              <Button variant="outline" className="w-full border-amber-300 text-amber-800 hover:bg-amber-100">
                Save Itinerary
              </Button>
              <Button variant="outline" className="w-full border-red-300 text-red-800 hover:bg-red-50">
                Share with Friends
              </Button>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default Itinerary;
